### ISSUE TITLE
anchor links that have parameter do not work

### ISSUE THREAD

**Issue by wighawag** [enzonotario/vitepress-openapi#108]
### Current behavior

in a setup where all operations are sown in one page, the table of content contains links to each one of them as anchor links

The operation that have parameters in their url (using`{}`) have their links not working

### Desired behavior

I expect all links to work

### Steps to reproduce

git clone https://github.com/wighawag/fuzd.git
cd fuzd
git checkout feat/vitepress-openapi
pnpm i
pnpm docs:dev
# navigate to http://localhost:5173/api-all-in-one/
# click on links

**Comment by enzonotario** [comment]
Hi @wighawag , it's now fixed by #117 , you can try it via [pkg-pr-new release](https://github.com/enzonotario/vitepress-openapi/runs/32567448431) until we get a new release. You can also see a working example in [StackBlitz](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-xwi16z?file=docs%2F.vitepress%2Ftheme%2Findex.ts)

Thanks for reporting!
