### ISSUE TITLE
Shorter badges for HTTP keywords, maybe?

### ISSUE THREAD

**Issue by stereobooster** [enzonotario/vitepress-openapi#118]
### What would you like?

Current implementation for badges use full keyword

<img width="230" alt="Screenshot 2024-11-13 at 10 48 57" src="https://github.com/user-attachments/assets/67f25510-3201-4ca0-adb6-1a1addb36f9e">

I thought maybe it would make sense to shorten them, so all would be the same length

<img width="239" alt="Screenshot 2024-11-13 at 10 49 46" src="https://github.com/user-attachments/assets/2336868f-16a6-458a-8cdd-879a13f56291">

### Why is this needed?

For esthetic purposes. Just an idea though

### How could it be implemented?

Use shorter keywords. Maybe it can be configurable

**Comment by stereobooster** [comment]
One more option. Use `display: block` instead of `display: flex`

<img width="231" alt="Screenshot 2024-11-13 at 10 54 35" src="https://github.com/user-attachments/assets/97162aef-7f46-4d73-a871-c774ffd90f72">

**Comment by enzonotario** [comment]
Hi @stereobooster , I like the idea to make it configurable, because it even allows to use it as a i18n config for other languages. So now in [v0.0.3-alpha.48](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.48) you can configure [`methodAliases`](https://vitepress-openapi.vercel.app/layouts/sidebar.html#method-aliases) to achieve this. For example: https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-fg9jcm?file=docs%2F.vitepress%2Fconfig.ts

![image](https://github.com/user-attachments/assets/e3e5462b-8a4a-404f-9777-1d94bc0876b6)


Regarding to flex/block style, I don't really see a difference by using `block`, so for now I prefer to keep using `flex`, considering that it can still be customized by custom styles.

Thanks for the suggestions! Any feedback from the release is welcome!
