### ISSUE TITLE
Allow using custom components in operations

### ISSUE THREAD

**Issue by ashercoren** [enzonotario/vitepress-openapi#89]
### What would you like?

Vitepress has the ability to define [custom components](https://vitepress.dev/guide/extending-default-theme#registering-global-components) which can later on be used across the documentation.

It would be nice if we could use such custom components in the generated api operations.

**Comment by enzonotario** [comment]
Hi @ashercoren! I don't understand at all what you specifically mean.

1. If you want to declare an `CustomTryButton` for example, and that the project uses it instead of the own library `OATryButton`, it may be possible, maybe just re-declaring Vue Components, but you will have to implement it as expected (just change html/css). I'd avoid this.

2. If you want to include some custom Vue components inside the rendered OpenAPI Spec. In this case, you can do this by using [Custom Slots](https://vitepress-openapi.vercel.app/layouts/custom-slots.html). You can even replace entire sections and implement them by yourself.

For example: https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-hrwwfe?file=docs%2Foperations%2F%5BoperationId%5D.md

These slots are not documented yet, you can see available slots in [`OAPath` component](https://github.com/enzonotario/vitepress-openapi/blob/main/src/components/Path/OAPath.vue). PRs are welcome!

Also, you can use any Markdown/Vue component before/after rendering the OpenAPI (via `OAOperation` or `OASpec`), as you can see in [ArgentinaDatos](https://argentinadatos.com/docs/operations/get-cotizaciones-dolares.html). [This page](https://github.com/enzonotario/esjs-argentina-datos-api/blob/main/docs/docs/operations/get-cotizaciones-dolares.md?plain=1) includes a [Part File that contains Markdown and Vue components](https://github.com/enzonotario/esjs-argentina-datos-api/blob/main/docs/docs/operations/parts/get-cotizaciones-dolares-casa-footer.md?plain=1)

**Comment by ashercoren** [comment]
Thanks @enzonotario. I'll look into the idea of using slots.

**Comment by enzonotario** [comment]
Nice! I'll close this issue. Feel free to re-open if needed, or to open other Issues.

Thanks!
